"""
Leetcode 389: Find the difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
"""

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        char_count = Counter(s)
        
        for char in t:
            char_count[char] -= 1

            if char_count[char] < 0:
                return char


class Solution2:
    def findTheDifference(self, s: str, t: str) -> str:
        orig_char_list = list(s)
        for c in t:
            if c not in orig_char_list:
                return c
            else:
                char_list.remove(c)
